name: Create Release Candidate

# Trigger when a PR is merged to main
on:
  push:
    branches:
      - main

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to create tags and branches
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      # Step 3: Set up Node.js (required for nodejs release type)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust to your project's Node version
      
      # Step 4: Install dependencies (if package.json exists)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          fi
      
      # Step 5: Download release scripts to /tmp (outside git)
      - name: Download release management scripts
        run: |
          # Use /tmp to avoid git tracking issues
          SCRIPT_DIR="/tmp/release-scripts-$$"
          mkdir -p "$SCRIPT_DIR"
          cd "$SCRIPT_DIR"
          
          # Set variables (using master for deprecated version)
          REF="${{ vars.RELEASE_SCRIPT_REF || 'master' }}"
          TYPES="${{ vars.RELEASE_TYPES || 'nodejs' }}"
          
          echo "=========================================="
          echo "Downloading scripts from ref: $REF"
          echo "Types: $TYPES"
          echo "Script directory: $SCRIPT_DIR"
          echo "=========================================="
          
          # Download the main release script
          curl -s -f -o release https://raw.githubusercontent.com/frontedgedigital/release-management/$REF/release || {
            echo "Failed to download release script"
            exit 1
          }
          chmod +x release
          
          # Download type-specific scripts
          for type in $TYPES; do
            echo "Downloading release-$type"
            curl -s -f -o release-$type https://raw.githubusercontent.com/frontedgedigital/release-management/$REF/release-$type || {
              echo "Failed to download release-$type script"
              exit 1
            }
            chmod +x release-$type
          done
          
          # Download tagging script
          curl -s -f -o tag-nodejs https://raw.githubusercontent.com/frontedgedigital/release-management/$REF/tag-nodejs || {
            echo "Warning: Failed to download tag-nodejs script"
          }
          chmod +x tag-nodejs 2>/dev/null || true
          
          # Save script directory for next steps
          echo "SCRIPT_DIR=$SCRIPT_DIR" >> $GITHUB_ENV
          
          cd "$GITHUB_WORKSPACE"
      
      # Step 6: Ensure clean git working directory
      - name: Clean git working directory
        run: |
          echo "Checking git status..."
          git status
          
          # Show untracked files
          echo ""
          echo "Untracked files:"
          git ls-files --others --exclude-standard
          
          # If there are any untracked files (like .release-scripts/), add them to .gitignore
          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
            echo ""
            echo "Adding untracked files to .gitignore..."
            
            # Create or append to .gitignore
            if [ ! -f .gitignore ]; then
              touch .gitignore
            fi
            
            # Add .release-scripts if it exists and not already ignored
            if [ -d .release-scripts ] && ! grep -q ".release-scripts" .gitignore 2>/dev/null; then
              echo ".release-scripts/" >> .gitignore
              git add .gitignore
              git commit -m "chore: ignore release scripts directory [skip ci]"
            fi
          fi
          
          echo ""
          echo "Final git status:"
          git status --short
      
      # Step 7: Execute the release candidate creation
      - name: Create Release Candidate
        env:
          HUSKY_SKIP_HOOKS: 1
          GIT_COMMIT_OPTS: --no-verify
          GIT_PUSH_OPTS: --no-verify
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get types and format them (space to plus conversion)
          TYPES="${{ vars.RELEASE_TYPES || 'nodejs' }}"
          TYPES_FORMATTED=$(echo -n "$TYPES" | tr ' ' '+')
          
          echo "=========================================="
          echo "Creating Release Candidate"
          echo "Types: $TYPES_FORMATTED"
          echo "Release Level: pre"
          echo "Working Directory: $(pwd)"
          echo "Package.json exists: $([ -f package.json ] && echo 'YES' || echo 'NO')"
          echo "Script location: $SCRIPT_DIR/release"
          echo "=========================================="
          
          # Add the script directory to PATH so release script can find its dependencies
          export PATH="$SCRIPT_DIR:$PATH"
          
          # Execute the release script from root directory
          # The scripts need to find package.json in the current directory
          # Usage: ./release <type> <release-level>
          "$SCRIPT_DIR/release" $TYPES_FORMATTED pre
      
      # Step 7: Push changes (in case script doesn't auto-push)
      - name: Push changes
        run: |
          echo "Pushing tags and branches..."
          git push --follow-tags --no-verify || echo "Push completed (may have been already pushed by script)"
      
      # Step 8: Output the created tag
      - name: Get created tag
        id: get_tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "unknown")
          echo "Created tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          
          # Get all tags created in this run
          echo "All recent tags:"
          git tag --sort=-creatordate | head -5
      
      # Step 9: Get RC branch if created
      - name: Get RC branch
        id: get_branch
        run: |
          # Check if an RC branch was created
          rc_branch=$(git branch -r | grep -E 'origin/.*-pre\.' | head -1 | sed 's/origin\///' | xargs || echo "none")
          echo "rc_branch=$rc_branch" >> $GITHUB_OUTPUT
          echo "RC Branch: $rc_branch"
      
      # Step 10: Create GitHub Release
      - name: Create GitHub Release
        if: steps.get_tag.outputs.tag != 'unknown'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release Candidate ${{ steps.get_tag.outputs.tag }}
          body: |
            🚀 Release Candidate created from merge to main
            
            **Details:**
            - Tag: `${{ steps.get_tag.outputs.tag }}`
            - Branch: `${{ steps.get_branch.outputs.rc_branch }}`
            - Commit: ${{ github.sha }}
            - Author: @${{ github.actor }}
            
            **Triggered by:** Merge to main
            
            This is a pre-release version for testing.
          draft: false
          prerelease: true
      
      # Step 11: Job summary
      - name: Job Summary
        if: always()
        run: |
          echo "### Release Candidate Creation Summary 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Created Tag:** \`${{ steps.get_tag.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**RC Branch:** \`${{ steps.get_branch.outputs.rc_branch }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "- Deploy tag \`${{ steps.get_tag.outputs.tag }}\` to staging/test environment" >> $GITHUB_STEP_SUMMARY
          echo "- Test the release candidate" >> $GITHUB_STEP_SUMMARY
          echo "- Promote to production when ready" >> $GITHUB_STEP_SUMMARY